// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2_H-l6i9lk53jh-REUs45QiQKhSxqIS4',
    appId: '1:1063594777818:web:52fb15932633cf40a759e3',
    messagingSenderId: '1063594777818',
    projectId: 'btl-android-506a1',
    authDomain: 'btl-android-506a1.firebaseapp.com',
    storageBucket: 'btl-android-506a1.firebasestorage.app',
    measurementId: 'G-VFC5GPDBVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnbCwoyyXRd1Fzvz3BxV-XAdccX4c1Zu0',
    appId: '1:1063594777818:android:c726d2b4f05d8619a759e3',
    messagingSenderId: '1063594777818',
    projectId: 'btl-android-506a1',
    storageBucket: 'btl-android-506a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA55CzFkAGCt0tIvV0BAIye0oP-vYXlZXQ',
    appId: '1:1063594777818:ios:c681b8cdd470570ba759e3',
    messagingSenderId: '1063594777818',
    projectId: 'btl-android-506a1',
    storageBucket: 'btl-android-506a1.firebasestorage.app',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA55CzFkAGCt0tIvV0BAIye0oP-vYXlZXQ',
    appId: '1:1063594777818:ios:c681b8cdd470570ba759e3',
    messagingSenderId: '1063594777818',
    projectId: 'btl-android-506a1',
    storageBucket: 'btl-android-506a1.firebasestorage.app',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2_H-l6i9lk53jh-REUs45QiQKhSxqIS4',
    appId: '1:1063594777818:web:334be5e8cb1f0672a759e3',
    messagingSenderId: '1063594777818',
    projectId: 'btl-android-506a1',
    authDomain: 'btl-android-506a1.firebaseapp.com',
    storageBucket: 'btl-android-506a1.firebasestorage.app',
    measurementId: 'G-HSSH1F97K6',
  );
}
